name: PSScriptAnalyzer

defaults:
  run:
    shell: pwsh

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '22 1 * * 3'

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: read
      security-events: write
    name: PSScriptAnalyzer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install AnyPackage and ConvertToSARIF
        run: Install-Module AnyPackage, ConvertToSARIF -Force -AllowClobber

      - name: Run PSScriptAnalyzer
        run: |
          Import-Module AnyPackage, ConvertToSARIF
          Invoke-ScriptAnalyzer -Path . -Recurse | ConvertTo-SARIF -FilePath results.sarif

      - name: Upload SARIF results file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
